const mongoose = require( 'mongoose' );

/**
 * A schema is just an abstract representation of our data in MongoDB.
 * We can enforce a certain field
 * - to be of particular type
 * - to be required
 * - to be unique
 * - to contain only specified characters
 *
 * A model is a more practical object with methods to query, remove, update
 * and save data from/to MongoDB.
 */
const characterSchema = new mongoose.Schema({
  characterId: { type: String, unique: true, index: true },
  name:      String,
  race:      String,
  gender:    String,
  bloodline: String,
  wins:      { type: Number, default: 0 },
  losses:    { type: Number, default: 0 },
  reports:   { type: Number, default: 0 },
  random:    { type: [Number], index: '2d' },
  voted:     { type: Boolean, default: false }
});

/*
random:
- An array of two numbers generated by [Math.random(), 0]
- A geospatial point as far as MongoDB is concerned
- In order to grab a random character from the database we will use the $near operator

voted:
- A boolean for identifying which characters have already been voted.
 */

module.exports = mongoose.model( 'Character', characterSchema );
